server:
  servlet:
    encoding:
      force: true
    context-path: /api-dev
  tomcat:
    uri-encoding: UTF-8
    accept-count: 1000 #连接数满后的排队数，默认100
    threads:
      max: 800 # 最大线程数 默认100
      min-spare: 100 # Tomcat 启动初始化的线程数，默认值为10
spring:
  security:
    user:
      name: root
      password: 123456
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 1000MB # 单个文件最大大小
      max-request-size: 1000MB # 最大请求大小
  # 数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tony-flowable?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: 123456
  # redis 配置
#  redis:
#    host: localhost
#    port: 6379
#    database: 0
#    password:
#    connect-timeout: 10s
#    lettuce:
#      pool:
#        min-idle: 0 #最小空闲连接
#        max-idle: 8 #最大空闲连接
#        max-active: 8 #连接池最大数据库连接数
#        max-wait: -1ms #连接池最大阻塞等待时间（负数代表没有限制）


# ORM框架配置
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.sai.springsecurity.**.infra.model.entity
  configuration:
    map-underscore-to-camel-case: true  # 下划线转驼峰
    lazy-loading-enabled: true # 开启延时加载
    cache-enabled: false # 不启用二级缓存，可能出现脏读
    aggressive-lazy-loading: false #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
  global-config:
    db-config:
      id-type: AUTO # 0 数据库id自增 , 1 用户输入id , 2 全局唯一id , 3 全局唯一uuid
      logic-delete-field: delflag
      logic-not-delete-value: 0
      logic-delete-value: 1

# 日志配置
logging:
  level:
    com.sai: debug # 包下的日志输出级别
    com.springframework: warn
    root: info # 当前项目所有的日志输出级别
  file:
    name: springsecurity.log  # 大小超过10M后会自动生成一个日志文件
#    path: logs
  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'

# 自定义swagger配置
swagger:
  enable: true
  applicationName: ${spring.application.name}
  version: 1.0.0